# Generated by Django 4.2.30 on 2026-09-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['-created_at'], name='routes_rout_created_6f595f_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', '-created_at'], name='routes_rout_user_id_983ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start_latitude', 'start_longitude'], name='routes_rout_start_l_faaa5f_idx'),
        ),
        migrations.AddField(
            model_name='routeimage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='routes.route'),
        ),
    ]
