# Generated by Django 4.2.30 on 2026-05-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_title_route_name_route_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='routes.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
